import { Product } from './types';

const IMG = (id: string, w = 800) =>
  `https://images.unsplash.com/${id}?w=${w}&q=80&fit=crop`;

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Custom Car Garage Key Holder',
    description: 'Organize your keys in style with this 3D printed car garage key holder. Features multiple hooks and a realistic garage design.',
    price: 399,
    originalPrice: 499,
    category: 'Accessories',
    image: IMG('photo-1558618666-fcd25c85cd64'),
    stock: 25,
    inStock: true,
    rating: 4.5,
    reviews: 18,
    madeToOrder: true,
    badge: 'Popular',
    collection: 'Home & Living',
    productionTime: 'Ships within 2-3 days',
    durabilityRating: 'moderate-use',
    specs: {
      material: 'PLA',
      dimensions: '20cm x 15cm x 8cm',
      printTime: '6 hours',
      infill: '20%',
      layerHeight: '0.2mm',
      supportRequired: false,
    },
  },
  {
    id: '2',
    name: 'Ghost Skull Mask',
    description: 'Spooky and stylish 3D printed ghost skull mask. Perfect for Halloween, cosplay, or as a unique wall decoration.',
    price: 799,
    originalPrice: 999,
    category: 'Costumes',
    image: IMG('photo-1509248961895-40c8c9705f1c'),
    stock: 15,
    inStock: true,
    rating: 4.7,
    reviews: 32,
    madeToOrder: true,
    badge: 'Bestseller',
    collection: 'Halloween & Cosplay',
    productionTime: 'Ships within 3-5 days',
    durabilityRating: 'light-use',
    specs: {
      material: 'PET-G',
      dimensions: '25cm x 20cm x 15cm',
      printTime: '12 hours',
      infill: '15%',
      layerHeight: '0.2mm',
      supportRequired: true,
    },
  },
  {
    id: '3',
    name: 'Loopy Chill Lamp (Crimson Edition)',
    description: 'Relaxing ambient lamp with a unique loopy design. Crimson edition features a warm red glow perfect for cozy spaces.',
    price: 799,
    originalPrice: 999,
    category: 'Home Decor',
    image: IMG('photo-1507473885765-e6ed056f785c'),
    stock: 12,
    inStock: true,
    rating: 4.8,
    reviews: 45,
    madeToOrder: true,
    badge: 'Fan favourite',
    collection: 'Lighting',
    productionTime: 'Ships within 3-5 days',
    durabilityRating: 'light-use',
    specs: {
      material: 'Translucent Red PLA',
      dimensions: '18cm x 18cm x 25cm',
      printTime: '14 hours',
      infill: '10%',
      layerHeight: '0.15mm',
      supportRequired: true,
    },
  },
  {
    id: '4',
    name: 'NFC Instagram Keychain',
    description: 'Smart NFC keychain that links to your Instagram profile. Just tap your phone to instantly follow or view your profile.',
    price: 299,
    originalPrice: 399,
    category: 'Tech',
    image: IMG('photo-1563770095-39d468fbb404'),
    stock: 50,
    inStock: true,
    rating: 4.6,
    reviews: 67,
    madeToOrder: true,
    badge: 'Top rated',
    collection: 'Smart Accessories',
    productionTime: 'Ships within 1-2 days',
    durabilityRating: 'moderate-use',
    specs: {
      material: 'PLA + NFC Tag',
      dimensions: '5cm x 5cm x 0.5cm',
      printTime: '1 hour',
      infill: '100%',
      layerHeight: '0.2mm',
      supportRequired: false,
    },
  },
  {
    id: '5',
    name: 'Shy Lamp™',
    description: 'Adorable shy lamp that looks away when you get close. Features motion sensor and expressive design.',
    price: 799,
    originalPrice: 999,
    category: 'Home Decor',
    image: IMG('photo-1513506003901-1e6a229e2d15'),
    stock: 10,
    inStock: true,
    rating: 4.9,
    reviews: 89,
    madeToOrder: true,
    badge: 'Trending',
    collection: 'Lighting',
    productionTime: 'Ships within 4-6 days',
    durabilityRating: 'light-use',
    specs: {
      material: 'White PLA',
      dimensions: '15cm x 15cm x 20cm',
      printTime: '10 hours',
      infill: '15%',
      layerHeight: '0.2mm',
      supportRequired: true,
    },
  },
  {
    id: '6',
    name: 'Spider-Man Mask with Texture',
    description: 'Highly detailed 3D printed Spider-Man mask with realistic web texture. Perfect for cosplay or display.',
    price: 2999,
    originalPrice: 3499,
    category: 'Costumes',
    image: IMG('photo-1635805737707-575885ab0820'),
    stock: 5,
    inStock: true,
    rating: 4.8,
    reviews: 23,
    madeToOrder: true,
    badge: 'Premium',
    collection: 'Superhero Collection',
    productionTime: 'Ships within 5-7 days',
    durabilityRating: 'light-use',
    specs: {
      material: 'Dual-tone PLA',
      dimensions: '30cm x 25cm x 20cm',
      printTime: '24 hours',
      infill: '12%',
      layerHeight: '0.15mm',
      supportRequired: true,
    },
  },
  {
    id: '7',
    name: 'Spider-Man String Art',
    description: 'Creative string art featuring Spider-Man design. Made with 3D printed frame and colorful threads.',
    price: 399,
    originalPrice: 499,
    category: 'Art',
    image: IMG('photo-1547891654-e66ed7ebb968'),
    stock: 20,
    inStock: true,
    rating: 4.4,
    reviews: 15,
    madeToOrder: true,
    collection: 'String Art',
    productionTime: 'Ships within 2-3 days',
    durabilityRating: 'display-only',
    specs: {
      material: 'PLA Frame + Thread',
      dimensions: '25cm x 25cm',
      printTime: '4 hours',
      infill: '20%',
      layerHeight: '0.2mm',
      supportRequired: false,
    },
  },
  {
    id: '8',
    name: 'Wobbly Penguin',
    description: 'Cute wobbly penguin toy that always stands back up. Great for desk decoration or as a fun gift.',
    price: 299,
    originalPrice: 399,
    category: 'Toys',
    image: IMG('photo-1558618666-fcd25c85cd64'),
    stock: 35,
    inStock: true,
    rating: 4.7,
    reviews: 56,
    madeToOrder: true,
    badge: 'Cute',
    collection: 'Toys & Figurines',
    productionTime: 'Ships within 1-2 days',
    durabilityRating: 'moderate-use',
    specs: {
      material: 'PET-G',
      dimensions: '8cm x 8cm x 12cm',
      printTime: '3 hours',
      infill: '25%',
      layerHeight: '0.2mm',
      supportRequired: true,
    },
  },
];